//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAPInsurancesTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPolicy
    {
        public int client_policy_id { get; set; }
        public int client_id { get; set; }
        public int policy_id { get; set; }
        public System.DateTime start_date { get; set; }
        public int coverage_period { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Policy Policy { get; set; }
    }
}
