//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAPInsurancesTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskType
    {
        public int risk_type_id { get; set; }
        public string risk_type { get; set; }
    }
}
